server:
  port: 17081
  servlet:
    context-path: /mongodb-api

management:
  server:
    port: 17082
#    servlet:
#      context-path: /management
  endpoints:
    web:
      base-path: /management
      exposure:
        include: "*"
        
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
  data:
    mongodb:
      uri: ${MONGODB_URL}
  jackson:
    property-naming-strategy: SNAKE_CASE
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}

mq:
  application: springboot-mongodb-api
  exchange: apis.direct
  in-queue-name: neo4j.queue
  out-queue-key: mongodb.key

logging:
  level:
    root: INFO
    